#!/bin/bash

# Darwin Marmolejos
# CIS-245-O1A
# March 14, 2026

# This script dumps network information to the terminal and saves it to a file. 
# The output file is saved to ~/network_reports/ with the date, my name, and purpose in the filename.

# Run from any directory. No special permissions needed unless 
# you want full port/process info (use sudo for that).

# Example: bash network_dump_darwin.sh
  sudo bash network_dump_darwin.sh

# Output: ~/network_reports/network_dump_darwin_YYYY-MM-DD.txt

 
# Get today's date for the filename
DATE=$(date +"%Y-%m-%d")
 
# Create the output directory if it doesn't exist
OUTDIR="$HOME/network_reports"
mkdir -p "$OUTDIR"
 
# Build the output filename with date, name, and purpose
OUTFILE="$OUTDIR/network_dump_darwin_${DATE}.txt"
 
# This function prints to both the terminal and the file at the same time.
# Using tee -a so every line shows up in both places.
out() {
    echo "$1" | tee -a "$OUTFILE"
}
 
# Print a section header with a separator line to keep things readable
section() {
    out ""
    out "=================================================================="
    out "  $1"
    out "=================================================================="
    out ""
}
 
# Print the command being run so the reader knows what generated the output
runcmd() {
    out "--- Command: $1 ---"
    eval "$1" 2>&1 | tee -a "$OUTFILE"
    out ""
}
 
# Start of Report
 
# Clear the file if it already exists from a previous run today
> "$OUTFILE"
 
out "=================================================================="
out "  NETWORK INFORMATION DUMP"
out "  Generated by: Darwin Marmolejos"
out "  Date: $(date)"
out "  Host: $(hostname)"
out "=================================================================="
 
# Section 1: System Info
# Starting with system info so whoever reads this knows what machine 
# they're looking at. hostnamectl gives OS, kernel, and hostname in one shot.


section "SYSTEM INFORMATION"
runcmd "hostnamectl"
 
# uname -a is a quick one-liner for kernel version and architecture
out "--- Command: uname -a ---"
uname -a 2>&1 | tee -a "$OUTFILE"
out ""
 
# uptime shows how long the server has been running and the load average
out "--- Command: uptime ---"
uptime 2>&1 | tee -a "$OUTFILE"
out ""
 
# Section 2: Network Interfaces
# ip a is the main command for seeing all interfaces, IPs, MACs, and 
# whether they're up or down. This is usually the first thing you check.

section "NETWORK INTERFACES"
runcmd "ip a"
 
# ip link show gives a cleaner view of just the interface status and MTU
# without all the address info cluttering it up

runcmd "ip link show"
 
# Section 3: IP Addresses
# ip -br a gives a brief one-line-per-interface summary which is easier 
# to scan quickly than the full ip a output

section "IP ADDRESSES (BRIEF)"
runcmd "ip -br a"
 
# Section 4: Routing Table
# The routing table shows how traffic gets from this server to other networks.
# The default route is the most important - that's the gateway to the internet.

section "ROUTING TABLE"
runcmd "ip r"
 
# Section 5: DNS Configuration
# DNS is what translates domain names to IPs. resolv.conf shows what DNS 
# servers the system is using. On Ubuntu this might show 127.0.0.53 
# (the systemd-resolved stub), on CentOS it shows the actual servers.

section "DNS CONFIGURATION"
runcmd "cat /etc/resolv.conf"
 
# If resolvectl is available (Ubuntu with systemd-resolved), show the 
# detailed DNS info per interface

if command -v resolvectl &> /dev/null; then
    out "--- resolvectl is available, showing detailed DNS info ---"
    runcmd "resolvectl status"
fi
 
# Section 6: Hostname and Hosts File

section "HOSTNAME & HOSTS FILE"
runcmd "cat /etc/hostname"
runcmd "cat /etc/hosts"
 
# Section 7: Listening Ports
# ss -tulnp shows what services are listening on what ports. This is 
# critical for security - you want to know what's exposed on the network.
# -t = TCP, -u = UDP, -l = listening, -n = numeric, -p = process name

section "LISTENING PORTS & SERVICES"
runcmd "ss -tulnp"
 
# Section 8: Active Connections
# ss -tun (without -l) shows established connections, so you can see 
# what the server is actively talking to right now

section "ACTIVE CONNECTIONS"
runcmd "ss -tun"
 
# Section 9: Firewall Status
# Check which firewall is running. Ubuntu typically uses ufw, CentOS uses 
# firewalld. We check for both so this script works on either server.

section "FIREWALL STATUS"

if command -v ufw &> /dev/null; then
    out "--- Detected: ufw (Ubuntu) ---"
    runcmd "sudo ufw status verbose"
elif command -v firewall-cmd &> /dev/null; then
    out "--- Detected: firewalld (CentOS) ---"
    runcmd "sudo firewall-cmd --list-all"
else
    out "No recognized firewall tool found (ufw or firewall-cmd)."
fi
 
# Section 10: Network Config Files 
# Show the actual config file so whoever reads this report can see exactly 
# how the network is configured, not just the current runtime state.

section "NETWORK CONFIGURATION FILES"
 
# Check for Netplan (Ubuntu)
if ls /etc/netplan/*.yaml &> /dev/null 2>&1; then
    out "--- Detected: Netplan (Ubuntu) ---"
    for f in /etc/netplan/*.yaml; do
        out "--- File: $f ---"
        cat "$f" 2>&1 | tee -a "$OUTFILE"
        out ""
    done
fi
 
# Check for NetworkManager connections (CentOS)
if ls /etc/NetworkManager/system-connections/*.nmconnection &> /dev/null 2>&1; then
    out "--- Detected: NetworkManager keyfiles (CentOS) ---"
    for f in /etc/NetworkManager/system-connections/*.nmconnection; do
        out "--- File: $f ---"
        sudo cat "$f" 2>&1 | tee -a "$OUTFILE"
        out ""
    done
fi
 
# nmcli connection details if available
if command -v nmcli &> /dev/null; then
    out "--- NetworkManager connection summary ---"
    runcmd "nmcli connection show"
    runcmd "nmcli device status"
fi
 
# Section 11: ARP Table 
# ARP maps IP addresses to MAC addresses on the local network. Useful for 
# seeing what other devices the server has communicated with recently.

section "ARP TABLE (NEIGHBOR CACHE)"
runcmd "ip neigh"
 
# Section 12: Connectivity Test
# A quick ping test to make sure the server can actually reach the internet.
# Using Google's DNS (8.8.8.8) and google.com to test both IP and DNS resolution.

section "CONNECTIVITY TEST"
out "--- Pinging 8.8.8.8 (tests IP connectivity) ---"
ping -c 3 8.8.8.8 2>&1 | tee -a "$OUTFILE"
out ""
out "--- Pinging google.com (tests DNS resolution) ---"
ping -c 3 google.com 2>&1 | tee -a "$OUTFILE"
out ""
 
# Section 13: Traceroute
# Shows the path packets take to reach google.com. Each hop is a router 
# between this server and the destination. Useful for diagnosing where 
# network issues might be occurring.

section "TRACEROUTE TO google.com"
if command -v traceroute &> /dev/null; then
    runcmd "traceroute -m 15 google.com"
else
    out "traceroute not installed. Install with:"
    out "  Ubuntu: sudo apt install traceroute"
    out "  CentOS: sudo dnf install traceroute"
fi
 
# End of Report
section "END OF REPORT"
out "Report saved to: $OUTFILE"
out "Generated on: $(date)"
out ""
 
